name: nymea_network_manager
description: Flutter package to interact with nymea network manager in BT BLE
version: 0.0.1
homepage: https://github.com/mylisabox/nymea_network_manager

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter_blue: ">=0.7.2 <1.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
